### ISSUE TITLE
Не смог создать заезд

### ISSUE THREAD

**Issue by rustemnasyrov** [rustemnasyrov/boat-race-emulator#10]
Если это из за участников так быть не должно. У меня может быть 9 дорожек, но участников 6 или 7. Просто будут пустые дорожки
Status Code 422

Редактирование выдаёт ту же ошибку

![image](https://github.com/rustemnasyrov/boat-race-emulator/assets/64511520/3fc0f628-5c02-49ab-ae8a-d15417e24902)

**Comment by workpro** [comment]
@rustemnasyrov 
конечно дорожек может быть больше
а смысл заводить в интерфейс пустые дорожки? чтобы их показывать на экране где лодки едут??
мы же для этого сделали редактируемым номер дорожки
оператор расскаживает гребцов по лодкам(дорожкам) и указывает кого на какой номер поставил и не обязательно что все доступные дорожки занял

в общем я тут не вижу бага - если надо переделаем
но это в каком-то смысле перестраховка оператору что он всех назанчил на дорожки
только сообщения об ошибке выводить и все

**Comment by rustemnasyrov** [comment]
@workpro @vea-dev  У вас на реальных соревноания есть вода разделенная на 9 секций и ты там распределяешь народ. Тут тоже самое - у тебя есть 9 тренажёров на ДИСЦИПЛИНЕ. Не больше и не меньше. Определяется это числом тренажёров, может быть 4,5,9,12. Оператору, который забивает людей на заезды нужно это число что бы распределить. Оно не МЕНЯЕТСЯ за время проведения турнира. Другое дело сто из 9 я могу использовать 5. Но это означает лишь то, что на дорожках будет пусто. Поэтому мне нужно фиксированное число дорожек в заезде. Ближайшее соревнование 5. Если тяжело переделать просто забейте 5 по умолчанию и сто бы номер нельзя было менять.

**Comment by rustemnasyrov** [comment]
Все работет.
