### ISSUE TITLE
Вделять цветом надпись статус заезда ЗАВЕРШЕН

### ISSUE THREAD

**Issue by rustemnasyrov** [rustemnasyrov/boat-race-emulator#24]
![image](https://github.com/rustemnasyrov/boat-race-emulator/assets/64511520/dd628852-6666-4116-922b-71d48d24be46)

**Comment by vea-dev** [comment]
@rustemnasyrov  Только завершенный? Или по каждому цвета будут?

**Comment by rustemnasyrov** [comment]
Проскакивало в одной из задач про цвета. Лучше разные для всех состояний. Глазами видно сразу будет.

**Comment by rustemnasyrov** [comment]
#21 дублирование
