### ISSUE TITLE
Не сортировать дорожки пока не завершен заезд 

### ISSUE THREAD

**Issue by rustemnasyrov** [rustemnasyrov/boat-race-emulator#30]
Трое доехали и их порядок поменялся. Давай менять когда все доедут
![image](https://github.com/rustemnasyrov/boat-race-emulator/assets/64511520/03d80078-fdbf-4de6-b330-6e8bfc0d77be)

**Comment by rustemnasyrov** [comment]
во время проведения заезда номера дорожек скачут

**Comment by vea-dev** [comment]
> во время проведения заезда номера дорожек скачут

Так это место, а не дорожка, здесь дорожки не выведены

**Comment by rustemnasyrov** [comment]
@vea-dev Тогда это нужно заменить на номер дорожки и никого никуда не двигать и ничего не менять пока заезд не завершен. Ситуация из реальной жизни: Спортстмен на дистанции. Неполадки на тренажере. Мне кричат "пятая дорожка - неисправность". Мне нужно отметить у себя фамилию человека, я не могу её найти так как номера скачут.
