### ISSUE TITLE
Не работает экспорт в excel при удалённых дорожках 

### ISSUE THREAD

**Issue by rustemnasyrov** [rustemnasyrov/boat-race-emulator#37]
Существует заезд. Мы из него удалили дорожку. Осуществили заплыв и получили вот такую картину. При нажатии Скачать Excel ничего не происходит. Видимо это происходит из-за пустых дорожек. 
То же самое происходит если в заезде существуют пустые дорожки, не заполненные участниками.
![image](https://github.com/rustemnasyrov/boat-race-emulator/assets/64511520/a0dcb14e-4833-4080-820e-00cc72133a21)

**Comment by rustemnasyrov** [comment]
@vea-dev если удалить все пустые дорожки, то экспорт проходит.

**Comment by vea-dev** [comment]
Поправил в новой ветке. Там же сделал заезд из сокета только на странице просмотра пока
