### ISSUE TITLE
РАЗОБРАТЬСЯ С Моментом сохранения заезда

### ISSUE THREAD

**Issue by zhuravkov** [rustemnasyrov/boat-race-emulator#39]
Бэк добавляет обработку финиша, по всем финишировавшим можно по или с предыдущим условием по дистанции.
ОБРАБОТКА НЕДОПЛЫВШИХ

**Comment by rustemnasyrov** [comment]
Сейчас у тренажера есть дистанция и статус. Завершающих статуса два  Finish и Stop. 
Finish - прошли дистанцию. 
Stop - сошел с дистанции. 
Поэтому логика может быть такая.  

finish_count = 0
results = []
for trainer in trainers:
  if (trainer.distance >= target_diatsnce) or (trainer.state in ('stop', 'finish):
   finish_count += 1
   if trainer.state == 'finish':
     resuls.append(trainer)

if (Finish_count == len(trainers) or (была_нажата_кнопка_Финиш):
  здесь сохраняем результаты, но только для тех у кого состояние 'finish'
  остальных отбрасываем или ставим пустое время прохождения дистанции

**Comment by rustemnasyrov** [comment]
Что то ерунду я написал выше. Выходит если все stop, тот заезд завершается. В общем, Сергей приступишь к задаче, позвони - решим.
